"""Host input firewall (nftables `inet bng_filter`) with confirm-or-revert.

`apply` loads the new rules from a pending file and arms a systemd timer that
restores the last *confirmed* rules after CONFIRM_SECONDS. Only `confirm`
(run from a fresh SSH session, proving SSH still works) stops the timer and
persists the rules, so a rule that locks out SSH undoes itself.
The same file carries the subscriber forward filter (stateful, MSS clamp) and
the CGNAT SNAT table `ip bng_nat`, so both change under the same safety net.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

from app.config.model import BngConfig

RULES = Path("/etc/bng-platform/nftables/filter.nft")
PENDING = Path("/var/lib/bng-platform/filter.nft.pending")
REVERT_UNIT = "bng-fw-revert"
CONFIRM_SECONDS = 120
REVERT_SCRIPT = (f"nft delete table inet bng_filter; nft delete table ip bng_nat; "
                 f"if [ -f {RULES} ]; then nft -f {RULES}; fi; rm -f {PENDING}")


def render(cfg: BngConfig) -> str:
    up = cfg.uplink
    subs = ", ".join(str(n) for n in cfg.subscriber_networks())
    dae = ""
    if cfg.aaa == "radius":
        srcs = ", ".join(str(n) for n in cfg.radius.dae_sources())
        dae = f"        udp dport {cfg.radius.coa_port} ip saddr {{ {srcs} }} accept\n"
    mss = ("        tcp flags & (syn | rst) == syn tcp option maxseg size set rt mtu\n"
           if not cfg.nat or cfg.nat.mss_clamp else "")
    text = (
        "# generated by bng-platform - do not edit\n"
        "table inet bng_filter\n"
        "delete table inet bng_filter\n"
        "table ip bng_nat\n"
        "delete table ip bng_nat\n"
        "table inet bng_filter {\n"
        "    chain input {\n"
        "        type filter hook input priority filter; policy drop;\n"
        '        iif "lo" accept\n'
        "        ct state established,related accept\n"
        "        ct state invalid drop\n"
        "        meta l4proto { icmp, ipv6-icmp } accept\n"
        "        tcp dport 22 accept\n"
        f"{dae}"
        "    }\n"
        "    chain forward {\n"
        "        type filter hook forward priority filter; policy drop;\n"
        f"{mss}"
        "        ct state established,related accept\n"
        "        ct state invalid drop\n"
        f'        iifname "ppp*" oifname "{up}" ip saddr {{ {subs} }} counter accept\n'
        "    }\n"
        "}\n"
    )
    if cfg.nat:
        # nft accepts a port range only after a transport-protocol match, so
        # TCP/UDP get the port range and everything else (ICMP, GRE...) only the address.
        rules = ""
        for p in cfg.nat.pools:
            match = f'        oifname "{up}" ip saddr {{ {", ".join(map(str, p.subscribers))} }} '
            tag = f'persistent comment "nat-pool {p.name}"\n'
            rules += (f"{match}meta l4proto {{ tcp, udp }} counter snat to {p.snat_target()} {tag}"
                      f"{match}counter snat to {p.public_range()} {tag}")
        text += ("table ip bng_nat {\n"
                 "    chain postrouting {\n"
                 "        type nat hook postrouting priority srcnat; policy accept;\n"
                 f"{rules}"
                 "    }\n"
                 "}\n")
    return text


def parse_nat_counters(json_text: str) -> list[dict]:
    """Per-pool totals (each pool has a TCP/UDP rule and an other-protocols rule)."""
    pools: dict[str, dict] = {}
    for obj in json.loads(json_text).get("nftables", []):
        rule = obj.get("rule")
        if not rule or not rule.get("comment", "").startswith("nat-pool "):
            continue
        c = next((e["counter"] for e in rule["expr"] if "counter" in e), {})
        name = rule["comment"].removeprefix("nat-pool ")
        acc = pools.setdefault(name, {"pool": name, "packets": 0, "bytes": 0})
        acc["packets"] += c.get("packets", 0)
        acc["bytes"] += c.get("bytes", 0)
    return list(pools.values())


def nat_counters() -> list[dict]:
    p = subprocess.run(["nft", "-j", "list", "table", "ip", "bng_nat"], capture_output=True, text=True, timeout=10)
    return parse_nat_counters(p.stdout) if p.returncode == 0 else []


def _run(*argv: str) -> None:
    p = subprocess.run(argv, capture_output=True, text=True, timeout=30)
    if p.returncode != 0:
        raise RuntimeError(f"{' '.join(argv[:2])}: {p.stderr.strip()}")


def _disarm() -> None:
    subprocess.run(["systemctl", "stop", f"{REVERT_UNIT}.timer"], capture_output=True, timeout=30)
    subprocess.run(["systemctl", "reset-failed", f"{REVERT_UNIT}.service"], capture_output=True, timeout=30)


def apply(cfg: BngConfig) -> None:
    PENDING.parent.mkdir(parents=True, exist_ok=True)
    PENDING.write_text(render(cfg))
    _run("nft", "-c", "-f", str(PENDING))
    _disarm()
    _run("systemd-run", f"--unit={REVERT_UNIT}", f"--on-active={CONFIRM_SECONDS}", "/bin/sh", "-c", REVERT_SCRIPT)
    try:
        _run("nft", "-f", str(PENDING))
    except RuntimeError:
        _disarm()
        raise


def confirm() -> None:
    if not PENDING.exists():
        raise RuntimeError("no pending firewall change (already confirmed, or it was reverted)")
    _disarm()
    RULES.parent.mkdir(parents=True, exist_ok=True)
    RULES.write_text(PENDING.read_text())
    PENDING.unlink()
