"""Host input firewall (nftables `inet bng_filter`) with confirm-or-revert.

`apply` loads the new rules from a pending file and arms a systemd timer that
restores the last *confirmed* rules after CONFIRM_SECONDS. Only `confirm`
(run from a fresh SSH session, proving SSH still works) stops the timer and
persists the rules, so a rule that locks out SSH undoes itself.
Forwarded subscriber traffic is not filtered here (Phase 2).
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from app.config.model import BngConfig

RULES = Path("/etc/bng-platform/nftables/filter.nft")
PENDING = Path("/var/lib/bng-platform/filter.nft.pending")
REVERT_UNIT = "bng-fw-revert"
CONFIRM_SECONDS = 120
REVERT_SCRIPT = (f"nft delete table inet bng_filter; "
                 f"if [ -f {RULES} ]; then nft -f {RULES}; fi; rm -f {PENDING}")


def render(cfg: BngConfig) -> str:
    dae = ""
    if cfg.aaa == "radius":
        srcs = ", ".join(str(n) for n in cfg.radius.dae_sources())
        dae = f"        udp dport {cfg.radius.coa_port} ip saddr {{ {srcs} }} accept\n"
    return (
        "# generated by bng-platform - do not edit\n"
        "table inet bng_filter\n"
        "delete table inet bng_filter\n"
        "table inet bng_filter {\n"
        "    chain input {\n"
        "        type filter hook input priority filter; policy drop;\n"
        '        iif "lo" accept\n'
        "        ct state established,related accept\n"
        "        ct state invalid drop\n"
        "        meta l4proto { icmp, ipv6-icmp } accept\n"
        "        tcp dport 22 accept\n"
        f"{dae}"
        "    }\n"
        "}\n"
    )


def _run(*argv: str) -> None:
    p = subprocess.run(argv, capture_output=True, text=True, timeout=30)
    if p.returncode != 0:
        raise RuntimeError(f"{' '.join(argv[:2])}: {p.stderr.strip()}")


def _disarm() -> None:
    subprocess.run(["systemctl", "stop", f"{REVERT_UNIT}.timer"], capture_output=True, timeout=30)
    subprocess.run(["systemctl", "reset-failed", f"{REVERT_UNIT}.service"], capture_output=True, timeout=30)


def apply(cfg: BngConfig) -> None:
    PENDING.parent.mkdir(parents=True, exist_ok=True)
    PENDING.write_text(render(cfg))
    _run("nft", "-c", "-f", str(PENDING))
    _disarm()
    _run("systemd-run", f"--unit={REVERT_UNIT}", f"--on-active={CONFIRM_SECONDS}", "/bin/sh", "-c", REVERT_SCRIPT)
    try:
        _run("nft", "-f", str(PENDING))
    except RuntimeError:
        _disarm()
        raise


def confirm() -> None:
    if not PENDING.exists():
        raise RuntimeError("no pending firewall change (already confirmed, or it was reverted)")
    _disarm()
    RULES.parent.mkdir(parents=True, exist_ok=True)
    RULES.write_text(PENDING.read_text())
    PENDING.unlink()
