"""Aggregate CAKE on the uplink, both directions explicit.

  Customer -> Internet : uplink EGRESS root qdisc              (upload)
  Internet -> Customer : uplink INGRESS -> mirred -> IFB EGRESS (download)

Output is a plain /bin/sh script (/etc/bng-platform/tc/cake.sh) built only from
model-validated values, so boot-time application needs no Python. Only options
detected in the installed tc are emitted; cake_mq only if the kernel+tc have it.
No per-subscriber classes: per-session limits live in accel-ppp's shaper.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path

from app.config.model import BngConfig
from app.networking import guard

IFB = "bngifb0"
SCRIPT = Path("/etc/bng-platform/tc/cake.sh")          # run at boot by bng-qos.service
PENDING = Path("/var/lib/bng-platform/cake.sh.pending")
REVERT_UNIT = "bng-qos-revert"
KNOWN_OPTIONS = {
    "besteffort", "diffserv3", "diffserv4", "diffserv8",
    "flowblind", "srchost", "dsthost", "hosts", "flows", "dual-srchost", "dual-dsthost", "triple-isolate",
    "nat", "nonat", "wash", "nowash", "split-gso", "no-split-gso",
    "ack-filter", "ack-filter-aggressive", "no-ack-filter",
    "memlimit", "fwmark", "ptm", "atm", "noatm", "overhead", "raw", "conservative", "mpu",
    "ingress", "egress", "bandwidth", "rtt",
}


def parse_capabilities(help_text: str) -> set[str]:
    """Options `tc ... cake help` advertises (words, with '*' default markers removed)."""
    words = set(re.findall(r"[a-z][a-z0-9-]*", help_text.replace("*", "")))
    return words & KNOWN_OPTIONS


def _tc_ok(*args: str) -> bool:
    return subprocess.run(["tc", *args], capture_output=True, timeout=10).returncode == 0


def detect() -> dict:
    """Probe on loopback (added and removed again), never on a live interface."""
    help_text = subprocess.run(["tc", "qdisc", "add", "dev", "lo", "root", "cake", "help"],
                               capture_output=True, text=True, timeout=10)
    caps = {"options": parse_capabilities(help_text.stdout + help_text.stderr)}
    for kind in ("cake", "cake_mq"):
        caps[kind] = _tc_ok("qdisc", "add", "dev", "lo", "root", kind)
        if caps[kind]:
            _tc_ok("qdisc", "del", "dev", "lo", "root")
    return caps


def _qdisc(dev: str, d, c, ingress: bool, caps: dict) -> str:
    words = [d.diffserv, d.isolation, "nat" if c.nat else "nonat",
             "wash" if c.wash else "nowash", d.ack_filter, c.link_layer]
    if c.overhead is None:
        words.append("raw")
    else:
        words += ["overhead", str(c.overhead)]
    if c.mpu is not None:
        words += ["mpu", str(c.mpu)]
    if ingress:
        words.append("ingress")
    missing = [w for w in words if not w.lstrip("-").isdigit() and w not in caps["options"]]
    if missing:
        raise ValueError(f"installed tc does not support cake option(s): {', '.join(missing)}")
    return (f"tc qdisc replace dev {dev} root {c.mode} bandwidth {d.bandwidth_mbit}mbit "
            f"rtt {c.rtt_ms}ms " + " ".join(words))


def render(cfg: BngConfig, caps: dict) -> str:
    up = cfg.uplink
    out = [
        "#!/bin/sh",
        "# generated by bng-platform from /etc/bng-platform/config.yaml - do not edit",
        "# clear previous state (root falls back to the kernel default qdisc)",
        f"tc qdisc del dev {up} root 2>/dev/null || true",
        f"tc qdisc del dev {up} ingress 2>/dev/null || true",
        f"ip link del {IFB} 2>/dev/null || true",
    ]
    c = cfg.qos.cake if cfg.qos else None
    if c and c.enabled:
        if not caps.get(c.mode):
            raise ValueError(f"{c.mode} is not supported by this kernel/tc")
        out += [
            "set -e",
            "# Internet -> Customer (download): queue on IFB first, redirect installed last",
            f"ip link add {IFB} type ifb",
            f"ip link set {IFB} up",
            _qdisc(IFB, c.download, c, True, caps),
            f"tc qdisc add dev {up} handle ffff: ingress",
            f"tc filter add dev {up} parent ffff: matchall action mirred egress redirect dev {IFB}",
            "# Customer -> Internet (upload): uplink egress",
            _qdisc(up, c.upload, c, False, caps),
        ]
    return "\n".join(out) + "\n"


def _sh(path: Path) -> None:
    p = subprocess.run(["/bin/sh", str(path)], capture_output=True, text=True, timeout=60)
    if p.returncode != 0:
        raise RuntimeError(f"{path.name}: {p.stderr.strip()}")


def apply(cfg: BngConfig) -> None:
    """Run the new script under a revert timer: an ingress redirect on the uplink
    can black-hole management traffic, so confirm from a fresh SSH session."""
    text = render(cfg, detect())
    PENDING.parent.mkdir(parents=True, exist_ok=True)
    PENDING.write_text(text)
    up, ifb = cfg.uplink, IFB
    revert = (f"if [ -f {SCRIPT} ]; then /bin/sh {SCRIPT}; else tc qdisc del dev {up} root; "
              f"tc qdisc del dev {up} ingress; ip link del {ifb}; fi; rm -f {PENDING}")
    guard.arm(REVERT_UNIT, revert)
    try:
        _sh(PENDING)
    except RuntimeError:
        subprocess.run(["/bin/sh", "-c", revert], capture_output=True, timeout=60)
        guard.disarm(REVERT_UNIT)
        raise


def confirm() -> None:
    if not PENDING.exists():
        raise RuntimeError("no pending QoS change (already confirmed, or it was reverted)")
    guard.disarm(REVERT_UNIT)
    SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    SCRIPT.write_text(PENDING.read_text())
    os.chmod(SCRIPT, 0o755)
    PENDING.unlink()


def parse_cake_json(text: str) -> dict | None:
    """Root CAKE qdisc stats from `tc -s -j qdisc show dev X` (bandwidth option is bytes/s)."""
    for q in json.loads(text or "[]"):
        if q.get("kind") in ("cake", "cake_mq") and q.get("root"):
            tins = q.get("tins", [])
            return {
                "bandwidth_mbit": q.get("options", {}).get("bandwidth", 0) * 8 / 1e6,
                **{k: q.get(k, 0) for k in ("bytes", "packets", "drops", "overlimits", "backlog")},
                "ecn_mark": sum(t.get("ecn_mark", 0) for t in tins),
                "ack_drops": sum(t.get("ack_drops", 0) for t in tins),
                "peak_delay_us": max((t.get("peak_delay_us", 0) for t in tins), default=0),
                "avg_delay_us": max((t.get("avg_delay_us", 0) for t in tins), default=0),
            }
    return None


def status(cfg: BngConfig) -> dict:
    def show(dev: str) -> dict | None:
        p = subprocess.run(["tc", "-s", "-j", "qdisc", "show", "dev", dev], capture_output=True, text=True, timeout=10)
        return parse_cake_json(p.stdout) if p.returncode == 0 else None
    return {"upload (Customer->Internet, egress " + cfg.uplink + ")": show(cfg.uplink),
            "download (Internet->Customer, ingress " + cfg.uplink + " via " + IFB + ")": show(IFB)}
