"""Aggregate CAKE on the uplink, both directions explicit.

  Customer -> Internet : uplink EGRESS root qdisc              (upload)
  Internet -> Customer : uplink INGRESS -> mirred -> IFB EGRESS (download)

Output is a plain /bin/sh script (/etc/bng-platform/tc/cake.sh) built only from
model-validated values, so boot-time application needs no Python. Only options
detected in the installed tc are emitted; cake_mq only if the kernel+tc have it.
No per-subscriber classes: per-session limits live in accel-ppp's shaper.
"""
from __future__ import annotations

import re
import subprocess

from app.config.model import BngConfig

IFB = "bngifb0"
KNOWN_OPTIONS = {
    "besteffort", "diffserv3", "diffserv4", "diffserv8",
    "flowblind", "srchost", "dsthost", "hosts", "flows", "dual-srchost", "dual-dsthost", "triple-isolate",
    "nat", "nonat", "wash", "nowash", "split-gso", "no-split-gso",
    "ack-filter", "ack-filter-aggressive", "no-ack-filter",
    "memlimit", "fwmark", "ptm", "atm", "noatm", "overhead", "raw", "conservative", "mpu",
    "ingress", "egress", "bandwidth", "rtt",
}


def parse_capabilities(help_text: str) -> set[str]:
    """Options `tc ... cake help` advertises (words, with '*' default markers removed)."""
    words = set(re.findall(r"[a-z][a-z0-9-]*", help_text.replace("*", "")))
    return words & KNOWN_OPTIONS


def _tc_ok(*args: str) -> bool:
    return subprocess.run(["tc", *args], capture_output=True, timeout=10).returncode == 0


def detect() -> dict:
    """Probe on loopback (added and removed again), never on a live interface."""
    help_text = subprocess.run(["tc", "qdisc", "add", "dev", "lo", "root", "cake", "help"],
                               capture_output=True, text=True, timeout=10)
    caps = {"options": parse_capabilities(help_text.stdout + help_text.stderr)}
    for kind in ("cake", "cake_mq"):
        caps[kind] = _tc_ok("qdisc", "add", "dev", "lo", "root", kind)
        if caps[kind]:
            _tc_ok("qdisc", "del", "dev", "lo", "root")
    return caps


def _qdisc(dev: str, d, c, ingress: bool, caps: dict) -> str:
    words = [d.diffserv, d.isolation, "nat" if c.nat else "nonat",
             "wash" if c.wash else "nowash", d.ack_filter, c.link_layer]
    if c.overhead is None:
        words.append("raw")
    else:
        words += ["overhead", str(c.overhead)]
    if c.mpu is not None:
        words += ["mpu", str(c.mpu)]
    if ingress:
        words.append("ingress")
    missing = [w for w in words if not w.lstrip("-").isdigit() and w not in caps["options"]]
    if missing:
        raise ValueError(f"installed tc does not support cake option(s): {', '.join(missing)}")
    return (f"tc qdisc replace dev {dev} root {c.mode} bandwidth {d.bandwidth_mbit}mbit "
            f"rtt {c.rtt_ms}ms " + " ".join(words))


def render(cfg: BngConfig, caps: dict) -> str:
    up = cfg.uplink
    out = [
        "#!/bin/sh",
        "# generated by bng-platform from /etc/bng-platform/config.yaml - do not edit",
        "# clear previous state (root falls back to the kernel default qdisc)",
        f"tc qdisc del dev {up} root 2>/dev/null",
        f"tc qdisc del dev {up} ingress 2>/dev/null",
        f"ip link del {IFB} 2>/dev/null",
    ]
    c = cfg.qos.cake if cfg.qos else None
    if c and c.enabled:
        if not caps.get(c.mode):
            raise ValueError(f"{c.mode} is not supported by this kernel/tc")
        out += [
            "set -e",
            "# Internet -> Customer (download): queue on IFB first, redirect installed last",
            f"ip link add {IFB} type ifb",
            f"ip link set {IFB} up",
            _qdisc(IFB, c.download, c, True, caps),
            f"tc qdisc add dev {up} handle ffff: ingress",
            f"tc filter add dev {up} parent ffff: matchall action mirred egress redirect dev {IFB}",
            "# Customer -> Internet (upload): uplink egress",
            _qdisc(up, c.upload, c, False, caps),
        ]
    return "\n".join(out) + "\n"
