"""Render BngConfig into accel-ppp 1.14.0 configuration.

The main file never contains a secret. RADIUS server lines (which embed the
shared secret) go to a root-only file pulled in by `$include` as the last line
of [radius]; per 1.14.0 conf_file.c the included file must have no header.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from ipaddress import IPv4Network

from app.config.model import BngConfig

SECRETS_INCLUDE = "/etc/bng-platform/secrets/radius.conf"
LAB_CHAP_SECRETS = "/etc/bng-platform/lab/chap-secrets"
# accel's own dictionary plus WISPr (not shipped by accel-ppp); installed by install.sh next to it
# because $INCLUDE resolves relative to the including file (1.14.0 dict.c)
DICTIONARY = "/usr/local/share/accel-ppp/radius/dictionary.bng"
CLI_TCP = "127.0.0.1:2001"
LOG_DIR = "/var/log/accel-ppp"

# printable ASCII without space and comma (',' separates server= fields)
_SECRET_RE = re.compile(r"^[\x21-\x2b\x2d-\x7e]{8,128}$")


@dataclass(frozen=True)
class Rendered:
    main: str
    secrets: str


def _b(v: bool) -> str:
    return "1" if v else "0"


def _host_ranges(net: IPv4Network) -> list[str]:
    """accel-ppp 1.14.0 (ippool.c) hands out every address of a CIDR pool,
    including x.x.x.0 and x.x.x.255, which some CPEs reject. Emit per-/24
    `x.x.x.a-b` ranges without them; same-name lines append to one pool."""
    out = []
    for s in (net.subnets(new_prefix=24) if net.prefixlen < 24 else [net]):
        lo = max(int(s.network_address) & 255, 1)
        hi = min(int(s.broadcast_address) & 255, 254)
        if lo <= hi:
            out.append(f"{str(s.network_address).rsplit('.', 1)[0]}.{lo}-{hi}")
    return out


def render(cfg: BngConfig, radius_secret: str | dict[str, str] | None) -> Rendered:
    """radius_secret: the default secret, or {"": default, "<server address>": secret, ...}."""
    out: list[str] = ["# generated by bng-platform from /etc/bng-platform/config.yaml - do not edit"]

    def section(name: str, *lines: str | None) -> None:
        out.append(f"[{name}]")
        out.extend(line for line in lines if line is not None)
        out.append("")

    radius = cfg.aaa == "radius"
    section("modules", "log_file", "pppoe", "auth_pap", "auth_chap_md5", "auth_mschap_v2",
            "radius" if radius else "chap-secrets", "ippool", "shaper" if cfg.shaper else None)
    section("core", f"log-error={LOG_DIR}/core.log",
            f"thread-count={cfg.thread_count}" if cfg.thread_count else None)
    section("common", "check-ip=1")
    p = cfg.ppp
    section("ppp", "verbose=1", "min-mtu=1280", f"mtu={p.mtu}", f"mru={p.mru}", "ipv4=require",
            f"ipv6={p.ipv6}", f"lcp-echo-interval={p.lcp_echo_interval}",
            f"lcp-echo-failure={p.lcp_echo_failure}", "unit-cache=1000")
    e = cfg.pppoe
    section("pppoe", "verbose=1", f"ac-name={e.ac_name}",
            f"service-name={e.service_name}" if e.service_name else None,
            f"accept-any-service={_b(e.accept_any_service)}", f"pado-delay={e.pado_delay_ms}",
            f"padi-limit={e.padi_limit}", f"called-sid={e.called_sid}",
            f"ip-pool={cfg.ip_pools.default}",
            *(f"interface={i.name}" + (f",padi-limit={i.padi_limit}" if i.padi_limit is not None else "")
              for i in e.interfaces))
    if cfg.dns:
        section("dns", *(f"dns{n}={a}" for n, a in enumerate(cfg.dns, 1)))

    secrets = ""
    if radius:
        r = cfg.radius
        keys = radius_secret if isinstance(radius_secret, dict) else {"": radius_secret}
        per_server = {str(s.address): keys.get(str(s.address)) or keys.get("") for s in r.servers}
        default = keys.get("") or next(iter(per_server.values()))
        for who, sec in {**per_server, "dae-server": default}.items():
            if not sec or not _SECRET_RE.match(sec):
                raise ValueError(f"RADIUS secret for {who} missing or invalid "
                                 "(8-128 printable ASCII characters, no space or comma)")
        section("radius", f"dictionary={DICTIONARY}", f"nas-identifier={r.nas_identifier}",
                f"nas-ip-address={r.nas_ip_address}", f"gw-ip-address={cfg.ip_pools.gw_ip_address}",
                f"timeout={r.timeout}", f"max-try={r.max_try}", f"acct-timeout={r.acct_timeout}",
                f"acct-interim-interval={r.acct_interim_interval}",
                f"acct-interim-jitter={r.acct_interim_jitter}",
                "dae-allowed=" + ",".join(str(n) for n in r.dae_sources()),
                f"blast-protection={_b(r.blast_protection)}",
                f"bind={r.bind}" if r.bind else None,
                "strip-realm=1" if r.strip_realm else None,
                f"default-realm={r.default_realm}" if r.default_realm else None,
                "verbose=1",
                f"$include {SECRETS_INCLUDE}")

        def opts(s) -> str:  # serv.c parse_server2 options; 0 leaves accel's default
            tuned = (("req-limit", s.req_limit), ("fail-timeout", s.fail_timeout), ("max-fail", s.max_fail))
            return ("".join(f",{k}={v}" for k, v in tuned if v) + (f",weight={s.weight}" if s.weight != 1 else "")
                    + (",backup" if s.backup else ""))
        secrets = "".join(
            f"server={s.address},{per_server[str(s.address)]},auth-port={s.auth_port},acct-port={s.acct_port}"
            f"{opts(s)}\n" for s in r.servers
        ) + f"dae-server={r.coa_listen}:{r.coa_port},{default}\n"
    else:
        section("chap-secrets", f"gw-ip-address={cfg.ip_pools.gw_ip_address}",
                f"chap-secrets={LAB_CHAP_SECRETS}")

    ip = cfg.ip_pools
    section("ip-pool", f"gw-ip-address={ip.gw_ip_address}", "attr=Framed-Pool",
            *(f"{rng},name={pl.name}" + (f",next={pl.next}" if pl.next else "")
              for pl in ip.pools for rng in _host_ranges(pl.network)))
    if cfg.shaper:
        s = cfg.shaper
        attrs = [f"attr-down={s.attr_down}", f"attr-up={s.attr_up}"] if s.attr_down else [f"attr={s.attr}"]
        # always emit vendor=: 1.14.0 shaper.c only assigns conf_vendor when the option is present, so a
        # reload that drops vendor=WISPr kept looking Filter-Id up under WISPr and disabled all shaping
        # ("incorrect attribute(s), tbf disabled"). vendor=0 -> parse_vendor_opt -> 0 = no vendor.
        section("shaper", *attrs, f"vendor={s.vendor or 0}",
                f"rate-multiplier={s.rate_multiplier:g}" if s.rate_multiplier else None,
                f"down-limiter={s.down_limiter}", f"up-limiter={s.up_limiter}", "verbose=1")
    section("log", f"log-file={LOG_DIR}/accel-ppp.log", f"log-emerg={LOG_DIR}/emerg.log", "level=3")
    section("cli", f"tcp={CLI_TCP}", "verbose=1")
    return Rendered("\n".join(out), secrets)
